### ISSUE TITLE
Cloned, doesn't run

### ISSUE THREAD

**Issue by amandapouget** [gkoberger/express4-mongoose-api-example#2]
Cloned the app.
Ran "npm install"
Changed "config.example.js" to "config.js"
Ran "npm start"

Got this result:
[nodemon] 1.9.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: _._
[nodemon] starting `node app.js`
module.js:341
    throw err;
    ^

Error: Cannot find module 'mongodb/node_modules/bson'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/amandasimon/Desktop/RoleModel/ExampleMongooseApp/node_modules/mongoose/lib/drivers/node-mongodb-native/objectid.js:8:16)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by rohitah** [comment]
Update your mongodb to latest version in package.json file and run npm install
